version: '3'

services: 
  app:
    image: docker.io/ossuchas/happyrefundapi:v1.24.1
    build:
        context: .
        dockerfile: ./Dockerfile
    ports: 
      - "5000:5000"
    expose:
      - "5000"
